-- Feature 13: production-grade department scope.
--
-- Existing RBAC policies remain permissive. These new restrictive policies are
-- AND-combined with them, so a capability still needs a same-department target.

create schema if not exists private;
revoke all on schema private from public, anon;

-- ---------------------------------------------------------------------------
-- Departments and profile membership
-- ---------------------------------------------------------------------------

create table public.departments (
  id integer generated by default as identity primary key,
  name text not null,
  protected boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint departments_name_check check (
    name = btrim(name)
    and char_length(name) between 2 and 80
  )
);

create unique index departments_name_lower_idx
  on public.departments (lower(name));

alter table public.departments enable row level security;

revoke all on table public.departments from anon, authenticated, public;
grant select on table public.departments to authenticated;
grant insert (name) on table public.departments to authenticated;
grant update (name) on table public.departments to authenticated;
grant usage, select on sequence public.departments_id_seq to authenticated;

insert into public.permissions (key)
values ('department.manage')
on conflict (key) do nothing;

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from public.roles r
cross join public.permissions p
where r.name = 'admin'
  and p.key = 'department.manage'
on conflict do nothing;

create policy "departments_select"
on public.departments
for select
to authenticated
using ((select public.is_active()));

create policy "departments_insert"
on public.departments
for insert
to authenticated
with check ((select public.has_permission('department.manage')));

create policy "departments_update"
on public.departments
for update
to authenticated
using ((select public.has_permission('department.manage')))
with check ((select public.has_permission('department.manage')));

create function public.normalize_department_name()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'UPDATE'
     and old.protected
     and new.name is distinct from old.name then
    raise exception 'protected departments cannot be renamed';
  end if;

  new.name := btrim(new.name);
  return new;
end;
$$;

create trigger departments_normalize_name
before insert or update of name on public.departments
for each row execute function public.normalize_department_name();

create trigger departments_set_updated_at
before update on public.departments
for each row execute function public.set_updated_at();

revoke execute on function public.normalize_department_name()
  from anon, authenticated, public;

insert into public.departments (name, protected)
values ('General', true);

alter table public.profiles
  add column department_id integer
  references public.departments(id) on delete restrict;

update public.profiles
set department_id = (
  select d.id from public.departments d where d.name = 'General'
)
where department_id is null;

do $$
begin
  if exists (
    select 1 from public.profiles where department_id is null
  ) then
    raise exception 'Feature 13 backfill left profiles without a department';
  end if;
end;
$$;

alter table public.profiles
  alter column department_id set not null;

create index profiles_department_id_idx
  on public.profiles (department_id);

-- ---------------------------------------------------------------------------
-- Central department helper
-- ---------------------------------------------------------------------------

create function private.can_access_user(target_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles me
    join public.profiles target on target.id = target_user_id
    where me.id = (select auth.uid())
      and me.deleted_at is null
      and (
        (select public.has_permission('user.manage_all'))
        or me.department_id = target.department_id
      )
  );
$$;

grant usage on schema private to authenticated;
grant execute on function private.can_access_user(uuid) to authenticated;
revoke execute on function private.can_access_user(uuid)
  from public, anon;

-- ---------------------------------------------------------------------------
-- Department isolation: restrictive policies layer over existing RBAC
-- ---------------------------------------------------------------------------

create policy "tasks_department_select"
on public.tasks
as restrictive
for select
to authenticated
using (private.can_access_user(assigned_to));

create policy "tasks_department_insert"
on public.tasks
as restrictive
for insert
to authenticated
with check (private.can_access_user(assigned_to));

create policy "tasks_department_update"
on public.tasks
as restrictive
for update
to authenticated
using (private.can_access_user(assigned_to))
with check (private.can_access_user(assigned_to));

create policy "submissions_department_select"
on public.submissions
as restrictive
for select
to authenticated
using (private.can_access_user(employee_id));

create policy "submissions_department_insert"
on public.submissions
as restrictive
for insert
to authenticated
with check (private.can_access_user(employee_id));

create policy "submissions_department_update"
on public.submissions
as restrictive
for update
to authenticated
using (private.can_access_user(employee_id))
with check (private.can_access_user(employee_id));

create policy "ratings_department_select"
on public.ratings
as restrictive
for select
to authenticated
using (private.can_access_user(employee_id));

create policy "ratings_department_insert"
on public.ratings
as restrictive
for insert
to authenticated
with check (private.can_access_user(employee_id));

create policy "activity_log_department_select"
on public.activity_log
as restrictive
for select
to authenticated
using (private.can_access_user(employee_id));

create policy "profiles_department_update"
on public.profiles
as restrictive
for update
to authenticated
using (private.can_access_user(id))
with check (private.can_access_user(id));

create policy "lifecycle_events_department_select"
on public.user_lifecycle_events
as restrictive
for select
to authenticated
using (private.can_access_user(target_user_id));

create policy "assignment_history_department_select"
on public.task_assignment_history
as restrictive
for select
to authenticated
using (
  (from_user_id is not null and private.can_access_user(from_user_id))
  or private.can_access_user(to_user_id)
);

-- ---------------------------------------------------------------------------
-- Department transfer history and concurrency-safe move
-- ---------------------------------------------------------------------------

create table public.user_department_history (
  id uuid primary key default gen_random_uuid(),
  request_id uuid unique not null,
  target_user_id uuid not null
    references public.profiles(id) on delete restrict,
  actor_id uuid references public.profiles(id) on delete restrict,
  from_department_id integer not null
    references public.departments(id) on delete restrict,
  to_department_id integer not null
    references public.departments(id) on delete restrict,
  reason text not null check (char_length(reason) between 3 and 500),
  created_at timestamptz not null default now(),
  constraint user_department_history_change_check
    check (from_department_id <> to_department_id)
);

create index user_department_history_target_created_idx
  on public.user_department_history (target_user_id, created_at desc);
create index user_department_history_actor_idx
  on public.user_department_history (actor_id)
  where actor_id is not null;
create index user_department_history_from_idx
  on public.user_department_history (from_department_id);
create index user_department_history_to_idx
  on public.user_department_history (to_department_id);

alter table public.user_department_history enable row level security;

revoke all on table public.user_department_history
  from anon, authenticated, public;
grant select on table public.user_department_history to authenticated;

create policy "user_department_history_select"
on public.user_department_history
for select
to authenticated
using (
  (select public.is_active())
  and private.can_access_user(target_user_id)
);

create trigger protect_user_department_history
before update or delete on public.user_department_history
for each row execute function public.reject_audit_mutation();

create function public.guard_profile_department()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.department_id is not distinct from old.department_id then
    return new;
  end if;

  if auth.uid() is not null
     and not public.has_permission('user.manage_all') then
    raise exception 'only a global manager may change a department';
  end if;

  return new;
end;
$$;

create trigger guard_profile_department
before update of department_id on public.profiles
for each row execute function public.guard_profile_department();

revoke execute on function public.guard_profile_department()
  from anon, authenticated, public;

create function public.audit_profile_department_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  context_request_id uuid;
  context_reason text;
begin
  if new.department_id is not distinct from old.department_id then
    return new;
  end if;

  context_request_id := coalesce(
    nullif(current_setting('meritly.department_request_id', true), '')::uuid,
    gen_random_uuid()
  );
  context_reason := coalesce(
    nullif(current_setting('meritly.department_reason', true), ''),
    'Direct department change'
  );

  insert into public.user_department_history (
    request_id,
    target_user_id,
    actor_id,
    from_department_id,
    to_department_id,
    reason
  ) values (
    context_request_id,
    new.id,
    auth.uid(),
    old.department_id,
    new.department_id,
    context_reason
  );

  return new;
end;
$$;

create trigger audit_profile_department_change
after update of department_id on public.profiles
for each row execute function public.audit_profile_department_change();

revoke execute on function public.audit_profile_department_change()
  from anon, authenticated, public;

create function public.move_user_department(
  p_request_id uuid,
  p_target_user_id uuid,
  p_new_department_id integer,
  p_reason text
)
returns table (
  from_department_id integer,
  to_department_id integer,
  duplicate_request boolean
)
language plpgsql
volatile
security invoker
set search_path = ''
as $$
declare
  clean_reason text := btrim(coalesce(p_reason, ''));
  caller_id uuid := auth.uid();
  current_department_id integer;
  existing_event public.user_department_history%rowtype;
begin
  if caller_id is null
     or not public.is_active()
     or not public.has_permission('user.manage_all') then
    raise exception 'user.manage_all is required to move departments';
  end if;

  if p_request_id is null then
    raise exception 'request id is required';
  end if;
  if p_target_user_id is null or p_target_user_id = caller_id then
    raise exception 'a different target user is required';
  end if;
  if char_length(clean_reason) not between 3 and 500 then
    raise exception 'reason must be between 3 and 500 characters';
  end if;

  select h.*
  into existing_event
  from public.user_department_history h
  where h.request_id = p_request_id
    and h.actor_id = caller_id;

  if found then
    return query
      select
        existing_event.from_department_id,
        existing_event.to_department_id,
        true;
    return;
  end if;

  if not exists (
    select 1 from public.departments d where d.id = p_new_department_id
  ) then
    raise exception 'destination department not found';
  end if;

  select p.department_id
  into current_department_id
  from public.profiles p
  where p.id = p_target_user_id
  for update;

  if not found then
    raise exception 'target user not found';
  end if;
  if current_department_id = p_new_department_id then
    raise exception 'target user is already in this department';
  end if;

  perform set_config(
    'meritly.department_request_id',
    p_request_id::text,
    true
  );
  perform set_config('meritly.department_reason', clean_reason, true);

  update public.profiles
  set department_id = p_new_department_id
  where id = p_target_user_id;

  select h.*
  into existing_event
  from public.user_department_history h
  where h.request_id = p_request_id;

  if not found then
    raise exception 'department audit event was not created';
  end if;

  return query
    select
      existing_event.from_department_id,
      existing_event.to_department_id,
      false;
end;
$$;

revoke execute on function public.move_user_department(
  uuid, uuid, integer, text
) from anon, public;
grant execute on function public.move_user_department(
  uuid, uuid, integer, text
) to authenticated;

-- ---------------------------------------------------------------------------
-- Trusted, service-only invite provisioning
-- ---------------------------------------------------------------------------

create table private.pending_user_provisioning (
  token uuid primary key default gen_random_uuid(),
  normalized_email text not null,
  full_name text not null,
  department_id integer not null
    references public.departments(id) on delete restrict,
  created_by uuid not null
    references public.profiles(id) on delete restrict,
  expires_at timestamptz not null default (now() + interval '30 minutes'),
  created_at timestamptz not null default now(),
  constraint pending_user_email_check
    check (normalized_email = lower(btrim(normalized_email))),
  constraint pending_user_name_check
    check (char_length(btrim(full_name)) between 2 and 120)
);

create unique index pending_user_provisioning_email_idx
  on private.pending_user_provisioning (normalized_email);
create index pending_user_provisioning_expiry_idx
  on private.pending_user_provisioning (expires_at);

revoke all on table private.pending_user_provisioning
  from public, anon, authenticated;

create function public.prepare_user_invite(
  p_email text,
  p_full_name text,
  p_department_id integer,
  p_created_by uuid
)
returns uuid
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  clean_email text := lower(btrim(coalesce(p_email, '')));
  clean_name text := btrim(coalesce(p_full_name, ''));
  new_token uuid;
begin
  delete from private.pending_user_provisioning
  where expires_at <= now();

  if clean_email = '' or clean_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' then
    raise exception 'invalid email';
  end if;
  if char_length(clean_name) not between 2 and 120 then
    raise exception 'full name must be between 2 and 120 characters';
  end if;
  if not exists (
    select 1 from public.departments d where d.id = p_department_id
  ) then
    raise exception 'department not found';
  end if;
  if not exists (
    select 1 from public.profiles p where p.id = p_created_by
  ) then
    raise exception 'invite actor not found';
  end if;

  insert into private.pending_user_provisioning (
    normalized_email,
    full_name,
    department_id,
    created_by
  ) values (
    clean_email,
    clean_name,
    p_department_id,
    p_created_by
  )
  on conflict (normalized_email) do update
  set
    full_name = excluded.full_name,
    department_id = excluded.department_id,
    created_by = excluded.created_by,
    token = gen_random_uuid(),
    expires_at = now() + interval '30 minutes',
    created_at = now()
  returning token into new_token;

  return new_token;
end;
$$;

create function public.cancel_user_invite_provisioning(p_token uuid)
returns void
language sql
volatile
security definer
set search_path = ''
as $$
  delete from private.pending_user_provisioning where token = p_token;
$$;

revoke execute on function public.prepare_user_invite(
  text, text, integer, uuid
) from public, anon, authenticated;
revoke execute on function public.cancel_user_invite_provisioning(uuid)
  from public, anon, authenticated;
grant execute on function public.prepare_user_invite(
  text, text, integer, uuid
) to service_role;
grant execute on function public.cancel_user_invite_provisioning(uuid)
  to service_role;

-- Compatibility version: a valid token is trusted, while the old deployed
-- invite route temporarily falls back to General. A later migration removes
-- the fallback after the new route is deployed.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  token_text text := new.raw_user_meta_data->>'meritly_provisioning_token';
  invite_token uuid;
  provision private.pending_user_provisioning%rowtype;
  provision_found boolean := false;
  general_department_id integer;
begin
  if token_text is not null
     and token_text ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then
    invite_token := token_text::uuid;

    select p.*
    into provision
    from private.pending_user_provisioning p
    where p.token = invite_token
      and p.normalized_email = lower(btrim(new.email))
      and p.expires_at > now()
    for update;

    provision_found := found;
  end if;

  if provision_found then
    insert into public.profiles (
      id,
      full_name,
      role_id,
      department_id
    ) values (
      new.id,
      provision.full_name,
      (select r.id from public.roles r where r.name = 'employee'),
      provision.department_id
    );

    delete from private.pending_user_provisioning
    where token = invite_token;
  else
    select d.id
    into general_department_id
    from public.departments d
    where d.name = 'General';

    insert into public.profiles (
      id,
      full_name,
      role_id,
      department_id
    ) values (
      new.id,
      coalesce(
        nullif(btrim(new.raw_user_meta_data->>'full_name'), ''),
        split_part(new.email, '@', 1)
      ),
      (select r.id from public.roles r where r.name = 'employee'),
      general_department_id
    );
  end if;

  return new;
end;
$$;

revoke execute on function public.handle_new_user()
  from anon, authenticated, public;

-- ---------------------------------------------------------------------------
-- Re-layer current live list/performance functions without dropping RBAC gates
-- ---------------------------------------------------------------------------

drop function public.admin_list_users();

create function public.admin_list_users()
returns table (
  id uuid,
  full_name text,
  role text,
  email text,
  deleted_at timestamptz,
  accepted boolean,
  department_id integer,
  department_name text
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  can_manage_all boolean := public.has_permission('user.manage_all');
begin
  if not (
    can_manage_all
    or public.has_permission('user.invite')
    or public.has_permission('user.promote')
    or public.has_permission('user.archive')
    or public.has_permission('stats.view_all')
  ) then
    raise exception 'not allowed to list users';
  end if;

  return query
    select
      p.id,
      p.full_name,
      r.name,
      u.email::text,
      p.deleted_at,
      (p.accepted_at is not null),
      d.id,
      d.name
    from public.profiles p
    join public.roles r on r.id = p.role_id
    join public.departments d on d.id = p.department_id
    join auth.users u on u.id = p.id
    where p.id <> auth.uid()
      and (
        can_manage_all
        or (
          r.assignable_work
          and private.can_access_user(p.id)
        )
      )
    order by p.created_at;
end;
$$;

revoke execute on function public.admin_list_users() from anon, public;
grant execute on function public.admin_list_users() to authenticated;

create or replace function public.assignable_employees()
returns table (id uuid, full_name text)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not (
    public.has_permission('task.create')
    or public.has_permission('task.update')
  ) then
    raise exception 'not allowed to list assignable employees';
  end if;

  return query
    select p.id, p.full_name
    from public.profiles p
    join public.roles r on r.id = p.role_id
    where p.deleted_at is null
      and r.assignable_work
      and p.accepted_at is not null
      and private.can_access_user(p.id)
    order by p.full_name;
end;
$$;

drop function public.historical_employees();

create function public.historical_employees()
returns table (
  id uuid,
  full_name text,
  role text,
  email text,
  deleted_at timestamptz,
  accepted boolean,
  current_assignable boolean,
  has_history boolean,
  department_id integer,
  department_name text
)
language plpgsql
stable
security invoker
set search_path = ''
as $$
begin
  if not public.has_permission('stats.view_all') then
    raise exception 'stats.view_all is required to list performance subjects';
  end if;

  return query
    with historical_ids as (
      select t.assigned_to as user_id from public.tasks t
      union
      select s.employee_id from public.submissions s
      union
      select a.employee_id from public.activity_log a
      union
      select h.from_user_id
      from public.task_assignment_history h
      where h.from_user_id is not null
      union
      select h.to_user_id from public.task_assignment_history h
      union
      select rt.employee_id from public.ratings rt
    ),
    subject_ids as (
      select p.id as user_id
      from public.profiles p
      join public.roles r on r.id = p.role_id
      where p.deleted_at is null
        and p.accepted_at is not null
        and r.assignable_work
      union
      select h.user_id from historical_ids h
    )
    select
      p.id,
      p.full_name,
      r.name,
      null::text,
      p.deleted_at,
      (p.accepted_at is not null),
      (
        p.deleted_at is null
        and p.accepted_at is not null
        and r.assignable_work
      ),
      exists (
        select 1 from historical_ids h where h.user_id = p.id
      ),
      d.id,
      d.name
    from subject_ids s
    join public.profiles p on p.id = s.user_id
    join public.roles r on r.id = p.role_id
    join public.departments d on d.id = p.department_id
    where p.id <> auth.uid()
      and private.can_access_user(p.id)
    order by p.created_at;
end;
$$;

revoke execute on function public.historical_employees()
  from anon, public;
grant execute on function public.historical_employees()
  to authenticated;

create or replace function public.can_view_performance_subject(target uuid)
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
  select
    case
      when target = auth.uid() then public.is_active()
      when not public.has_permission('stats.view_all') then false
      when not private.can_access_user(target) then false
      else exists (
        select 1
        from public.profiles p
        join public.roles r on r.id = p.role_id
        where p.id = target
          and (
            (
              p.deleted_at is null
              and p.accepted_at is not null
              and r.assignable_work
            )
            or exists (
              select 1 from public.tasks t where t.assigned_to = target
            )
            or exists (
              select 1
              from public.submissions s
              where s.employee_id = target
            )
            or exists (
              select 1
              from public.activity_log a
              where a.employee_id = target
            )
            or exists (
              select 1
              from public.task_assignment_history h
              where h.from_user_id = target or h.to_user_id = target
            )
            or exists (
              select 1 from public.ratings rt where rt.employee_id = target
            )
          )
      )
    end;
$$;
